# Generated by Django 5.2.1 on 2025-05-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='is_deleted',
            new_name='is_archived',
        ),
    ]
