# Generated by Django 5.2.1 on 2025-05-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Price for this specific variant. If blank, defaults to product's base price.", max_digits=10, null=True),
        ),
    ]
