# Generated by Django 5.2.1 on 2025-05-25 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_deleted_at_product_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecasted_quantity', models.IntegerField()),
                ('current_stock', models.IntegerField()),
                ('restock_needed', models.BooleanField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
