# Generated by Django 5.2.1 on 2025-05-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_restocklog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandchecklog',
            options={'ordering': ['-checked_at']},
        ),
        migrations.AddField(
            model_name='demandchecklog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandchecklog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
