# Generated by Django 5.2.1 on 2025-05-31 17:38

import apps.purchase_orders.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0001_initial'),
        ('store', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-order_date'], 'verbose_name_plural': 'Purchase Orders'},
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='expected_delivery',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, help_text='Estimated date for delivery of items.', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, help_text='Any additional notes for the purchase order.', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the purchase order was created.'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_order_id',
            field=models.CharField(default=apps.purchase_orders.models.generate_unique_purchase_order_id, editable=False, help_text='Unique identifier for the purchase order.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='received_date',
            field=models.DateField(blank=True, help_text='Actual date when all items were received.', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Confirmation'), ('ordered', 'Ordered'), ('partially_received', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', help_text='Current status of the purchase order.', max_length=30),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(help_text='The supplier from whom items are ordered.', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cost of all items in the purchase order.', max_digits=12),
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.PositiveIntegerField(help_text='The quantity of the product variant ordered.')),
                ('quantity_received', models.PositiveIntegerField(default=0, help_text='The quantity of the product variant actually received so far.')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='The cost per unit of the product variant at the time of order.', max_digits=10)),
                ('product_variant', models.ForeignKey(help_text='The specific product variant being ordered.', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items', to='store.productvariant')),
                ('purchase_order', models.ForeignKey(help_text='The purchase order this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase_orders.purchaseorder')),
            ],
            options={
                'verbose_name_plural': 'Purchase Order Items',
                'ordering': ['product_variant__product__name'],
                'unique_together': {('purchase_order', 'product_variant')},
            },
        ),
    ]
