# Generated by Django 5.2.1 on 2025-06-01 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0002_alter_purchaseorder_options_and_more'),
        ('store', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product_name_text',
            field=models.CharField(blank=True, help_text='Optional product name if no variant selected.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='The supplier from whom items are ordered.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, help_text='The specific product variant being ordered.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items', to='store.productvariant'),
        ),
    ]
