# Generated by Django 5.2.1 on 2025-06-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0003_purchaseorderitem_product_name_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for the order item.', null=True),
        ),
    ]
